framework:
    mailer:
        # un comment the lines bellow if you want to fix a sender
        envelope:
            # this overrides the `from` in mailer
            # internal default sender
            sender: '%env(MAILER_DEFAULT_SENDER)%'
        dsn: '%env(MAILER_DSN)%'
