twig:
    default_path: '%kernel.project_dir%/templates'

#    form_themes:
#        - 'forms/blog_theme.html.twig'
#        - 'bootstrap_5_layout.html.twig'
when@test:
    twig:
        strict_variables: true
